#!/usr/bin/env ruby
# frozen_string_literal: true

# compare_models.rb <solid_queue_tag>
#
# Fetches solid_queue model files at a given tag from GitHub and diffs them
# against the local Mongoid equivalents in lib/solid_queue_mongoid/models/.
# Outputs a Markdown report to STDOUT.

require "net/http"
require "json"
require "tmpdir"
require "fileutils"

TAG = ARGV[0] || abort("Usage: compare_models.rb <tag>")
UPSTREAM_REPO = "rails/solid_queue"
UPSTREAM_BASE  = "app/models/solid_queue"
LOCAL_BASE     = File.expand_path("../../lib/solid_queue_mongoid/models", __dir__)

# Map upstream path (relative to app/models/solid_queue) -> local path (relative to lib/solid_queue_mongoid/models)
# They share the same names so the mapping is 1:1 for direct files.
# Sub-directories are also 1:1.

def github_api(path)
  uri = URI("https://api.github.com/#{path}")
  req = Net::HTTP::Get.new(uri)
  req["Accept"] = "application/vnd.github+json"
  req["X-GitHub-Api-Version"] = "2022-11-28"
  req["Authorization"] = "Bearer #{ENV['GITHUB_TOKEN']}" if ENV["GITHUB_TOKEN"]
  resp = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |h| h.request(req) }
  JSON.parse(resp.body)
end

def raw_content(path, ref)
  uri = URI("https://raw.githubusercontent.com/#{UPSTREAM_REPO}/#{ref}/#{path}")
  req = Net::HTTP::Get.new(uri)
  req["Authorization"] = "Bearer #{ENV['GITHUB_TOKEN']}" if ENV["GITHUB_TOKEN"]
  resp = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |h| h.request(req) }
  resp.body
end

# Recursively collect all .rb files in upstream directory at given ref
def collect_upstream_files(dir_path, ref)
  entries = github_api("repos/#{UPSTREAM_REPO}/contents/#{dir_path}?ref=#{ref}")
  files = []
  entries.each do |entry|
    case entry["type"]
    when "file"
      files << entry["path"] if entry["name"].end_with?(".rb")
    when "dir"
      files.concat(collect_upstream_files(entry["path"], ref))
    end
  end
  files
rescue => e
  warn "Warning: could not list #{dir_path}: #{e.message}"
  []
end

puts "Fetching upstream file list for #{TAG}..."
upstream_files = collect_upstream_files(UPSTREAM_BASE, TAG)

results = { modified: [], new_upstream: [], missing_local: [] }
diffs   = {}

Dir.mktmpdir("solid_queue_compare") do |tmpdir|
  upstream_files.each do |upstream_path|
    # Convert upstream path to local relative path
    relative = upstream_path.delete_prefix("#{UPSTREAM_BASE}/")
    local_path = File.join(LOCAL_BASE, relative)

    upstream_content = raw_content(upstream_path, TAG)
    upstream_tmp = File.join(tmpdir, "upstream_#{relative.gsub('/', '_')}")
    File.write(upstream_tmp, upstream_content)

    if File.exist?(local_path)
      diff_out = `diff -u "#{local_path}" "#{upstream_tmp}" 2>&1`
      unless diff_out.empty?
        results[:modified] << relative
        diffs[relative] = diff_out
      end
    else
      results[:new_upstream] << relative
      diffs[relative] = upstream_content
    end
  end

  # Check for local files that no longer exist upstream
  Dir.glob("#{LOCAL_BASE}/**/*.rb").each do |local_path|
    relative = local_path.delete_prefix("#{LOCAL_BASE}/")
    upstream_path = "#{UPSTREAM_BASE}/#{relative}"
    unless upstream_files.include?(upstream_path)
      results[:missing_local] << relative
    end
  end
end

# ── Generate Markdown report ──────────────────────────────────────────────────

lines = []
lines << "## solid_queue `#{TAG}` — Model Diff Analysis"
lines << ""
lines << "This PR was automatically generated by comparing upstream `rails/solid_queue` model files"
lines << "at tag `#{TAG}` against the Mongoid equivalents in `lib/solid_queue_mongoid/models/`."
lines << ""

total_changes = results[:modified].size + results[:new_upstream].size + results[:missing_local].size
if total_changes.zero?
  lines << "> ✅ No model changes detected. Only the version tracking file has been updated."
else
  lines << "### Summary"
  lines << ""
  lines << "| File | Status |"
  lines << "|------|--------|"
  results[:modified].each      { |f| lines << "| `#{f}` | 🔄 Modified upstream |" }
  results[:new_upstream].each  { |f| lines << "| `#{f}` | 🆕 New in upstream (no local equivalent) |" }
  results[:missing_local].each { |f| lines << "| `#{f}` | ⚠️ Exists locally but removed from upstream |" }
  lines << ""

  unless results[:modified].empty?
    lines << "### Migration Checklist"
    lines << ""
    results[:modified].each      { |f| lines << "- [ ] Review and update `lib/solid_queue_mongoid/models/#{f}`" }
    results[:new_upstream].each  { |f| lines << "- [ ] Decide whether to add `lib/solid_queue_mongoid/models/#{f}`" }
    results[:missing_local].each { |f| lines << "- [ ] Decide whether to remove `lib/solid_queue_mongoid/models/#{f}`" }
    lines << ""
  end

  lines << "### Diffs"
  lines << ""
  diffs.each do |relative, diff|
    status = results[:new_upstream].include?(relative) ? "new upstream file" : "modified"
    lines << "<details>"
    lines << "<summary><code>#{relative}</code> — #{status}</summary>"
    lines << ""
    lines << "```diff"
    lines << diff
    lines << "```"
    lines << ""
    lines << "</details>"
    lines << ""
  end
end

puts lines.join("\n")

